# Generated by Django 5.2.6 on 2025-10-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.TextField(choices=[('NA', 'Not Applied'), ('AP', 'Applied'), ('RV', 'Review'), ('IV', 'Interview'), ('OF', 'Offer'), ('CL', 'Closed')], default='NA', max_length=2),
        ),
    ]
