# Generated by Django 5.2.6 on 2025-10-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AP', 'Applied'), ('RV', 'Review'), ('IV', 'Interview'), ('OF', 'Offer'), ('CL', 'Closed')], default='AP', max_length=2),
        ),
    ]
