# Generated by Django 5.0 on 2025-09-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_education_jobposting_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='links',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='remote_or_onsite',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(default='Not specified', help_text='e.g. $60,000 - $80,000', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='visa_sponsorship',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(default='', help_text='List required skills, separated by commas'),
        ),
    ]
