# Generated by Django 5.0 on 2025-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobposting_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='max_salary',
            field=models.IntegerField(default=0, help_text='Maximum annual salary (USD)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_salary',
            field=models.IntegerField(default=0, help_text='Minimum annual salary (USD)'),
        ),
    ]
