# Generated by Django 5.0 on 2025-10-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_fname_customuser_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commute_radius',
            field=models.IntegerField(default=50, help_text='Maximum commute radius in miles (0 for remote only)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='desired_max_salary',
            field=models.IntegerField(default=0, help_text='Desired maximum annual salary (USD)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='desired_min_salary',
            field=models.IntegerField(default=0, help_text='Desired minimum annual salary (USD)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_visa',
            field=models.BooleanField(default=False, help_text='Interested in visa sponsorship'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_remote',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('any', 'Any')], default='any', help_text='Preferred work arrangement', max_length=20),
        ),
    ]
