# Generated by Django 5.0 on 2025-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education',
            field=models.CharField(blank=True, help_text='Minimum required education', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='links',
            field=models.URLField(blank=True, help_text='Optional link for more info or application', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.TextField(blank=True, help_text='List required skills, separated by commas', null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_experience',
            field=models.TextField(blank=True, help_text='Describe required work experience', null=True),
        ),
    ]
