# Generated by Django 5.2.6 on 2025-10-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_active',
        ),
    ]
