# Generated by Django 5.2.6 on 2025-09-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
