# Generated by Django 5.0 on 2025-10-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDismissedJob',
        ),
    ]
