# Generated by Django 5.2.6 on 2025-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='num_of_matches',
            field=models.IntegerField(default=0),
        ),
    ]
